<?php
//    +-----------------------------------------------------------------------------+
//    OpenEMR - Open Source Electronic Medical Record
//    Copyright (C) 2014 Z&H Consultancy Services Private Limited <sam@zhservices.com>
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as
//    published by the Free Software Foundation, either version 3 of the
//    License, or (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//    Author:   Bindia Nandakumar <bindia@zhservices.com>
//
// +------------------------------------------------------------------------------+

$res = $this->view;
if($res != 0){
    foreach ($res as $view){
        var_dump($view);
    }
} else {
    echo "No results";
}

?>
<div class="row">
    <div id="col" class="col-lg-12 -align-self-center">
        <h3>CC Processing Center</h3>
        <div id="chargestable">
            <table class="table">
                <thead>
                    <th>id</th>
                    <th>pid</th>
                    <th>Patient Name</th>
                    <th>Charge Amt</th>
                    <th>encounter</th>
                    <th>DOS</th>
                    <th>Delay</th>
                </thead>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><input type="checkbox" value="2"></td>
                </tr>
            </table>

        </div>

    </div>
</div>

